# Generated by Django 4.0.6 on 2022-10-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
